version: '3'
services:
  neo4j:
    build:
      context: .
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/newpassroot
      #Senha para acesso a interface do neo4j
volumes:
  neo4j_data:
