version: '3'
services:
  cassandra:
    build:
      context: .
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=toor

volumes:
  cassandra_data:
